### ISSUE TITLE
Bundle's goal

### ISSUE THREAD

**Issue by igormukhingmailcom** [ibrows/IbrowsLoggableBundle#1]
Hi.
Can you please describe what problem is solving by this bundle?
There is no information about that in `README.md`.
Thanks a lot.

**Comment by Gladhon** [comment]
The bundle will track every Entity change on your Projekt and save it to a log table. Your Projekt get's some kind of confirmability with this Bundle.

It also provide some methods to get back an entity to a earlier version.

**Comment by igormukhingmailcom** [comment]
Wow. That awesome. 
Thank you for reply.
