### ISSUE TITLE
Loggable bundle

### ISSUE THREAD

**Issue by fcpauldiaz** [ibrows/IbrowsLoggableBundle#4]
Is this bundle maintained ? What is the difference between the [doctrine extensions] (https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/loggable.md) and this bundle?

**Comment by Gladhon** [comment]
This Bundle is build in top of the doctrine loggable extension.

It tracks every change on your database, also removements and reletion changes ( many-to-one for example ). Your Project get's some kind of confirmability with this Bundle.

Further it provides method's to get an old version ( by date or version ) of an Entity, so you can show users how entity has looked on an specific date.
It also provides methods to get all changes for an entity, it's also possible to get changes from related "Sub-Entites".

**Comment by mikemeier** [comment]
It's also used in productive environment of a customer project. So it is maintained.

**Comment by fcpauldiaz** [comment]
Thanks for the reply, I'm looking forward to test it.
